from datetime import datetime, timezone

from pgvector.sqlalchemy import Vector
from sqlalchemy import BigInteger, Boolean, Computed, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class FileRecord(Base):
    __tablename__ = "files"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    path: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    sha256: Mapped[str] = mapped_column(String, nullable=False, index=True)
    mime_type: Mapped[str] = mapped_column(String, nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    queue: Mapped[str] = mapped_column(String, nullable=False)
    # st_mtime_ns at last scan; with size_bytes lets the scan skip re-hashing
    # a file that hasn't changed. NULL until the first scan after this column
    # existed.
    mtime_ns: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    status: Mapped[str] = mapped_column(String, nullable=False, default="discovered")
    discovered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)

    # Document-intrinsic metadata, populated at convert time — NULL until
    # then, and still NULL after if the backend couldn't determine it.
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    author: Mapped[str | None] = mapped_column(Text, nullable=True)
    doc_created_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Keyword-searchable file metadata (title, author, filename). Lets a
    # query like "invoices from alice" match on the file itself, not just
    # on chunk text. Path separators become spaces so folder and file names
    # tokenize into words.
    meta_vector = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(author, '') || ' ' "
            "|| regexp_replace(path, '[/\\\\._-]', ' ', 'g'))",
            persisted=True,
        ),
    )

    jobs: Mapped[list["JobRecord"]] = relationship(back_populates="file")


class JobRecord(Base):
    __tablename__ = "jobs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    file_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("files.id", ondelete="CASCADE"))
    job_type: Mapped[str] = mapped_column(String, nullable=False)
    # Which Celery queue ran this job (its worker). Lets a restarting worker
    # close only ITS orphaned jobs -- the upload worker and the bulk convert
    # worker run the same job types. NULL on rows from before this column.
    queue: Mapped[str | None] = mapped_column(String, nullable=True)
    state: Mapped[str] = mapped_column(String, nullable=False, default="pending")
    retries: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)

    file: Mapped["FileRecord"] = relationship(back_populates="jobs")


class ChunkRecord(Base):
    __tablename__ = "chunks"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    file_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("files.id", ondelete="CASCADE"))
    text: Mapped[str] = mapped_column(Text, nullable=False)
    # Section heading this chunk came from (see summarization/chunker.py);
    # '' for rows indexed before the column existed.
    heading: Mapped[str] = mapped_column(Text, nullable=False, default="")
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    embedding = mapped_column(Vector(1024), nullable=True)
    # Keyword-search side of hybrid retrieval. Generated by Postgres from
    # heading + text, so it never needs to be set on insert and can't drift.
    search_vector = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', coalesce(heading, '') || ' ' || text)", persisted=True),
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class QueryHistoryRecord(Base):
    """One row per query run through /query or /query/upload. Stores the
    full result, not just the question: re-running a query against a local
    LLM is slow, so the History page restores the stored answer instead."""

    __tablename__ = "query_history"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    sources: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    grounded: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    cross_doc: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    statistical: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # filter_* rather than author/title: `files` already has title/author
    # columns meaning document-intrinsic metadata, and an unprefixed name
    # here would be ambiguous in any query joining both tables.
    filter_folders: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    filter_author: Mapped[str | None] = mapped_column(Text, nullable=True)
    filter_title: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Non-empty only for "+"-attach queries, which bypass the corpus.
    attached_filenames: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # True when this was a direct model chat (Ask page's Scope bar had
    # nothing selected) — no retrieval happened, so filter_folders is
    # meaningless here even though it's still stored as []. Lets the Ask
    # page's thread-persistence reconstruct each entry's mode on reload.
    chat_only: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Client-generated UUID (see dashboard/src/pages/Ask.tsx) grouping
    # turns into one chat thread — "New chat" is just a fresh id, no
    # server round-trip needed to start one. '' (the default) marks rows
    # from before this column existed; they're excluded from the
    # conversation list (see app/history/store.py:list_conversations)
    # but still reachable individually via /history/queries/{id}.
    conversation_id: Mapped[str] = mapped_column(Text, nullable=False, default="")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class ConversationPin(Base):
    """One row per pinned chat. Separate from query_history because a pin
    belongs to the conversation, not to any one of its messages — and
    unpinning is just deleting the row."""

    __tablename__ = "conversation_pins"

    conversation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    pinned_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class ExportHistoryRecord(Base):
    __tablename__ = "export_history"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    # SET NULL, not CASCADE: deleting a query shouldn't destroy the record
    # of a file that still exists on disk and is still downloadable.
    query_history_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("query_history.id", ondelete="SET NULL"), nullable=True
    )
    filename: Mapped[str] = mapped_column(Text, nullable=False)
    fmt: Mapped[str] = mapped_column(String, nullable=False)
    stored_path: Mapped[str] = mapped_column(Text, nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
